#!/usr/bin/env python3

# Copyright (c) 2016, Antonio SJ Musumeci <trapexit@spawn.link>

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import argparse
import errno
import hashlib
import os
import pickle
import random
import re
import shlex
import stat
import subprocess
import sys
import tempfile
import time


def build_arg_parser():
    desc = 'a tool to help discover file corruption'
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('-d','--db',
                        type=str,
                        required=True,
                        help='database which stores hashes')
    parser.add_argument('inst',
                        choices=['add','append','check',
                                 'check+update','delete',
                                 'cleanup','list',
                                 'list-unhashed','list-dups'],
                        help='actions')
    parser.add_argument('dir',
                        type=str,
                        nargs='+',
                        help='directories to work on')
    parser.add_argument('-v','--verbose',
                        action='store_true',
                        help='print details of files')
    parser.add_argument('-r','--restrict',
                        choices=['sticky',
                                 'readonly'],
                        help='restrict action to certain types of files')
    parser.add_argument('-f','--fnfilter',
                        type=str,
                        help='restrict action to files which match regex')
    parser.add_argument('-s','--sort',
                        choices=['none','radix','reverse-radix',
                                 'natural','reverse-natural','random'],
                        help='when adding/appending/checking sort files before acting on them')
    parser.add_argument('-m','--max',
                        type=int,
                        default=sys.maxsize,
                        help='max number of actions to take')

    return parser


def hash_file(filepath, hasher=None, blocksize=65536):
    if not hasher:
        hasher = hashlib.md5()

    try:
        with open(filepath,'rb') as afile:
            buf = afile.read(blocksize)
            while buf:
                hasher.update(buf)
                buf = afile.read(blocksize)
    except:
        pass

    return hasher.hexdigest()


def get_file_list(basepath,fnfilter,db=None):
    filelist = []
    for (dirname,dirnames,filenames) in os.walk(basepath):
        fulldirpath = os.path.join(basepath,dirname)
        for filename in filenames:
            filepath = os.path.join(fulldirpath,filename)
            if fnfilter(filepath):
                continue
            if db and filepath in db:
                continue
            filelist.append(filepath)
    return filelist


def filter_filepaths(filepaths,basepath,fnfilter,other=(lambda f: False)):
    rv = []
    for filepath in filepaths:
        if not filepath.startswith(basepath):
            continue
        if fnfilter(filepath):
            continue
        if other(filepath):
            continue
        rv.append(filepath)

    return rv


def get_stat(filepath):
    try:
        st = os.lstat(filepath)
        if not stat.S_ISREG(st.st_mode):
            return None
        return st
    except:
        return None


def print_filepath(count,total,filepath):
    padding = len(str(total))
    padded = str(count).zfill(padding)
    s = '{0}/{1} {2}: '.format(padded,total,filepath)
    print(s,end='')


# Can't use inode since filesystems based on FUSE can have those change
# mount to mount
def different_files(oldst,newst):
    return ((oldst.st_size  != newst.st_size) and
            (oldst.st_mtime != newst.st_mtime))


def add_hashes(db,basepath,restrict,fnfilter,sort,
               maxactions,verbose,dbadd,dbremove):
    rv = 1
    filepaths = get_file_list(basepath,fnfilter)
    sort(filepaths)

    actions = 0
    total = min(maxactions,len(filepaths))
    for filepath in filepaths:
        st = get_stat(filepath)
        if not st:
            continue
        if not restrict(st):
            continue

        if actions >= maxactions:
            return rv
        actions += 1

        rv = 0
        if verbose:
            print_filepath(actions,total,filepath)

        try:
            hashval = hash_file(filepath)
            dbadd[filepath] = (hashval,st)
            if verbose:
                print(hashval)
        except Exception as e:
            if verbose:
                print("ERROR:",e)

    return rv


def append_hashes(db,basepath,restrict,fnfilter,sort,
                  maxactions,verbose,dbadd,dbremove):
    rv = 1
    filepaths = get_file_list(basepath,fnfilter,db)
    sort(filepaths)

    actions = 0
    total = min(maxactions,len(filepaths))
    for filepath in filepaths:
        st = get_stat(filepath)
        if not st:
            continue
        if not restrict(st):
            continue

        if actions >= maxactions:
            return rv
        actions += 1

        rv = 0
        if verbose:
            print_filepath(actions,total,filepath)

        try:
            hashval = hash_file(filepath)
            dbadd[filepath] = (hashval,st)
            if verbose:
                print(hashval)
        except Exception as e:
            if verbose:
                print(e)

    return rv


def check_hashes(db,basepath,restrict,fnfilter,sort,
                 maxactions,verbose,dbadd,dbremove,update=False):
    rv = 0
    filepaths = filter_filepaths(db.keys(),basepath,fnfilter)
    sort(filepaths)

    actions = 0
    total = min(maxactions,len(filepaths))
    for filepath in filepaths:
        st = get_stat(filepath)
        if not st:
            continue
        if not restrict(st):
            continue

        if actions >= maxactions:
            return rv
        actions += 1

        if verbose:
            print_filepath(actions,total,filepath)

        try:
            oldst = db[filepath][1]
            if different_files(oldst,st):
                if not verbose:
                    print_filepath(actions,total,filepath)
                print("FILE CHANGED\n",
                      "- size:",oldst.st_size,st.st_size,"\n"
                      " - mtime:",int(oldst.st_mtime),int(st.st_mtime))
                if update:
                    hashval = hash_file(filepath)
                    dbadd[filepath] = (hashval,st)
                    print(" - updated hash:",hashval)
            else:
                hashval = hash_file(filepath)
                oldhashval = db[filepath][0]
                if hashval != oldhashval:
                    rv = 1
                    if not verbose:
                        print_filepath(actions,total,filepath)
                    print("FAILED")
                elif verbose:
                    print("OK")
        except Exception as e:
            if not verbose:
                print_filepath(actions,total,filepath)
            print('ERROR:',e)

    return rv


def check_and_update_hashes(db,basepath,restrict,fnfilter,sort,
                            maxactions,verbose,dbadd,dbremove):
    return check_hashes(db,basepath,restrict,fnfilter,sort,
                        maxactions,verbose,dbadd,dbremove,update=True)


def delete_hashes(db,basepath,restrict,fnfilter,sort,
                  maxactions,verbose,dbadd,dbremove):
    rv = 1
    filepaths = filter_filepaths(db.keys(),basepath,fnfilter)
    sort(filepaths)

    actions = 0
    total = min(maxactions,len(filepaths))
    for filepath in filepaths:
        st = get_stat(filepath)
        if st and not restrict(st):
            continue

        if actions >= maxactions:
            return rv
        actions += 1

        rv = 0
        dbremove.append(filepath)
        if verbose:
            print_filepath(actions,total,filepath)
            print("removed")

    return rv


def cleanup_hashes(db,basepath,restrict,fnfilter,sort,
                   maxactions,verbose,dbadd,dbremove):
    rv = 1
    filepaths = filter_filepaths(db.keys(),basepath,fnfilter,os.path.exists)
    sort(filepaths)

    actions = 0
    total = min(maxactions,len(filepaths))
    for filepath in filepaths:
        if actions >= maxactions:
            return rv
        actions += 1

        rv = 0
        dbremove.append(filepath)
        if verbose:
            print_filepath(actions,total,filepath)
            print("removed")

    return rv


def list_hashes(db,basepath,restrict,fnfilter,sort,
                maxactions,verbose,dbadd,dbremove):
    rv = 1
    filepaths = filter_filepaths(db.keys(),basepath,fnfilter)
    sort(filepaths)

    actions = 0
    for filepath in filepaths:
        (hashval,st) = db[filepath]
        if not restrict(st):
            continue

        if actions >= maxactions:
            return rv
        actions += 1

        rv = 0
        print("{0} {1}".format(hashval,filepath))

    return rv


def list_unhashed(db,basepath,restrict,fnfilter,sort,
                  maxactions,verbose,dbadd,dbremove):
    rv = 1
    filepaths = get_file_list(basepath,fnfilter,db)
    sort(filepaths)

    actions = 0
    for filepath in filepaths:
        st = get_stat(filepath)
        if not st:
            continue
        if not restrict(st):
            continue

        if actions >= maxactions:
            return rv
        actions += 1

        rv = 0
        print(filepath)

    return rv


def list_dups(db,basepath,restrict,fnfilter,sort,
              maxactions,verbose,dbadd,dbremove):
    rv = 1
    hashdb = {}
    for (filepath,(hashval,st)) in db.items():
        if not filepath.startswith(basepath):
            continue
        if fnfilter(filepath):
            continue
        if not restrict(st):
            continue

        if not hashval in hashdb:
            hashdb[hashval] = [filepath]
            continue

        hashdb[hashval].append(filepath)

    actions = 0
    for (hashval,filepaths) in hashdb.items():
        if len(filepaths) <= 1:
            continue

        if actions >= maxactions:
            return rv
        actions += 1

        rv = 0
        filepaths = [shlex.quote(filepath) for filepath in filepaths]
        filepaths.sort()
        print(hashval,' '.join(filepaths))

    return rv


def is_sticky(st):
    return bool(st.st_mode & stat.S_ISVTX)


def is_readonly(st):
    return not (st.st_mode & (stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH))


def restrict_fun(rtype):
    if rtype == 'sticky':
        return is_sticky
    elif rtype == 'readonly':
        return is_readonly
    return (lambda st: True)


def filter_fun(regex):
    if regex:
        cregex = re.compile(regex)
        return (lambda filepath: cregex.match(filepath) == None)
    return (lambda filepath: False)


def inst_fun(inst):
    if inst == 'add':
        return add_hashes
    elif inst == 'append':
        return append_hashes
    elif inst == 'check':
        return check_hashes
    elif inst == 'check+update':
        return check_and_update_hashes
    elif inst == 'delete':
        return delete_hashes
    elif inst == 'cleanup':
        return cleanup_hashes
    elif inst == 'list':
        return list_hashes
    elif inst == 'list-unhashed':
        return list_unhashed
    elif inst == 'list-dups':
        return list_dups
    return None


def sort_fun(sort):
    if sort == 'radix':
        return (lambda l: l.sort())
    elif sort == 'reverse-radix':
        return (lambda l: l.sort(reverse=True))
    elif sort == 'random':
        return (lambda l: random.shuffle(l))
    elif sort == 'natural':
        cre = re.compile('(\d+)')
        sort_key = lambda s: [int(t) if t.isdigit() else t.lower()
                              for t in re.split(cre,s)]
        return (lambda l: l.sort(key=sort_key))
    elif sort == 'reverse-natural':
        cre = re.compile('(\d+)')
        sort_key = lambda s: [int(t) if t.isdigit() else t.lower()
                              for t in re.split(cre,s)]
        return (lambda l: l.sort(key=sort_key,reverse=True))
    return (lambda l: None)


def read_db(filepath):
    db = {}
    try:
        with open(filepath,'rb') as f:
            db = pickle.load(f)
    except Exception as e:
        dirname = os.path.dirname(filepath)
        if not os.path.isdir(dirname):
            raise
    return db


def write_db(filepath,dbadd,dbremove):
    try:
        db = read_db(filepath)

        for (k,v) in dbadd.items():
            db[k] = v;
        for k in dbremove:
            del db[k]

        basepath = os.path.dirname(filepath)
        (fd,tmpfilepath) = tempfile.mkstemp(dir=basepath)
        with os.fdopen(fd,'wb') as f:
            pickle.dump(db,f)
        os.rename(tmpfilepath,filepath)
    except Exception as e:
        print('Error writing checksum DB:',e)


def main():
    parser = build_arg_parser()
    args = parser.parse_args()

    verbose = args.verbose
    restrict = restrict_fun(args.restrict)
    func = inst_fun(args.inst)
    sort = sort_fun(args.sort)
    fnfilter = filter_fun(args.fnfilter)
    maxactions = args.max

    rv = 0
    try:
        db = read_db(args.db)
        dbadd = {}
        dbremove = []

        for directory in args.dir:
            directory = os.path.realpath(directory)
            rv = rv or func(db,directory,restrict,fnfilter,sort,
                            maxactions,verbose,dbadd,dbremove)

        if len(dbadd) or len(dbremove):
            write_db(args.db,dbadd,dbremove)

    except KeyboardInterrupt:
        rv = 1
    except IOError as e:
        rv = 1
        if e.errno != errno.EPIPE:
            print(e)
    except Exception as e:
        rv = 1
        print(e)

    sys.exit(rv)


if __name__ == "__main__":
    main()
